using './main.bicep'

param location = 'eastus2'
param environmentName = 'dev'
param baseName = 'pipelinehealer'
param acrName = 'caneprophacr01'
param containerAppsEnvironmentName = 'cae-canepro-ph-dev-eus'
param backendContainerAppName = 'ca-canepro-ph-backend'
param frontendContainerAppName = 'ca-canepro-ph-frontend'
param backendImageName = 'pipelinehealer-backend'
param frontendImageName = 'pipelinehealer-frontend'
param imageTag = 'latest'
