using './main.bicep'

param location = 'eastus2'
param environmentName = 'prod'
param baseName = 'pipelinehealer'
param acrName = 'caneprophacrprod01'
param containerAppsEnvironmentName = 'cae-canepro-ph-prod-eus2'
param backendContainerAppName = 'ca-canepro-ph-prod-backend'
param frontendContainerAppName = 'ca-canepro-ph-prod-frontend'
param backendImageName = 'pipelinehealer-backend'
param frontendImageName = 'pipelinehealer-frontend'
param imageTag = 'v0.8.1'
param storageMode = 'cosmos'
param createCosmosDb = false
param cosmosDbEndpointOverride = 'https://pipelinehealerdev-cosmos-zarrajklt3i5u.documents.azure.com:443/'
param cosmosDbDatabaseName = 'pipelinehealer'
param createAzureOpenAi = false
param azureOpenAiEndpoint = ''
param azureOpenAiDeploymentName = ''
param llmProvider = 'codex_app_server'
param codexAppServerTransport = 'websocket'
param codexAppServerModel = readEnvironmentVariable('CODEX_APP_SERVER_MODEL', 'gpt-5.4')
param codexAppServerTurnTimeoutMs = int(readEnvironmentVariable('CODEX_APP_SERVER_TURN_TIMEOUT_MS', '180000'))
param codexAppServerWsUrl = readEnvironmentVariable('CODEX_APP_SERVER_WS_URL', '')
param codexAppServerWsAllowRemote = true
param codexAppServerWsBearerToken = readEnvironmentVariable('CODEX_APP_SERVER_WS_BEARER_TOKEN', '')
param apiAuthKey = readEnvironmentVariable('API_AUTH_KEY')
param adminApiKey = readEnvironmentVariable('ADMIN_API_KEY')
param githubWebhookSecret = readEnvironmentVariable('GITHUB_WEBHOOK_SECRET')
param githubPersonalAccessToken = readEnvironmentVariable('GITHUB_PERSONAL_ACCESS_TOKEN', '')
