using './main.bicep'

param location = 'eastus2'
param environmentName = 'prod'
param baseName = 'pipelinehealer'
param acrName = readEnvironmentVariable('PH_ACR_NAME', 'pipelinehealeracrprod')
param containerAppsEnvironmentName = readEnvironmentVariable('PH_CONTAINER_APPS_ENVIRONMENT_NAME', 'cae-pipelinehealer-prod')
param backendContainerAppName = readEnvironmentVariable('PH_BACKEND_APP', 'pipelinehealer-backend-prod')
param frontendContainerAppName = readEnvironmentVariable('PH_FRONTEND_APP', 'pipelinehealer-frontend-prod')
param backendImageName = 'pipelinehealer-backend'
param frontendImageName = 'pipelinehealer-frontend'
param imageTag = readEnvironmentVariable('RELEASE_VERSION', 'latest')
param storageMode = 'cosmos'
param createCosmosDb = false
param cosmosDbEndpointOverride = readEnvironmentVariable('COSMOS_DB_ENDPOINT', '')
param cosmosDbDatabaseName = 'pipelinehealer'
param createAzureOpenAi = false
param azureOpenAiEndpoint = ''
param azureOpenAiDeploymentName = ''
param llmProvider = 'codex_app_server'
param codexAppServerTransport = 'websocket'
param codexAppServerModel = readEnvironmentVariable('CODEX_APP_SERVER_MODEL', 'gpt-5.4')
param codexAppServerTurnTimeoutMs = int(readEnvironmentVariable('CODEX_APP_SERVER_TURN_TIMEOUT_MS', '180000'))
param codexAppServerWsUrl = readEnvironmentVariable('CODEX_APP_SERVER_WS_URL', '')
param codexAppServerWsAllowRemote = true
param codexAppServerWsBearerToken = readEnvironmentVariable('CODEX_APP_SERVER_WS_BEARER_TOKEN', '')
param apiAuthKey = readEnvironmentVariable('API_AUTH_KEY')
param authMode = readEnvironmentVariable('AUTH_MODE', 'hybrid')
param entraTenantId = readEnvironmentVariable('ENTRA_TENANT_ID', '')
param entraClientId = readEnvironmentVariable('ENTRA_CLIENT_ID', '')
param entraAllowedAudiences = readEnvironmentVariable('ENTRA_ALLOWED_AUDIENCES', '')
param entraAdminRoles = readEnvironmentVariable('ENTRA_ADMIN_ROLES', 'PipelineHealer.Admin')
param frontendAuthMode = readEnvironmentVariable('VITE_AUTH_MODE', 'entra')
param frontendEntraTenantId = readEnvironmentVariable('VITE_ENTRA_TENANT_ID', '')
param frontendEntraClientId = readEnvironmentVariable('VITE_ENTRA_CLIENT_ID', '')
param frontendEntraAuthority = readEnvironmentVariable('VITE_ENTRA_AUTHORITY', '')
param frontendEntraApiScope = readEnvironmentVariable('VITE_ENTRA_API_SCOPE', '')
param frontendEntraRedirectUri = readEnvironmentVariable('VITE_ENTRA_REDIRECT_URI', '')
param frontendEntraPostLogoutRedirectUri = readEnvironmentVariable('VITE_ENTRA_POST_LOGOUT_REDIRECT_URI', '')
param adminApiKey = readEnvironmentVariable('ADMIN_API_KEY')
param githubWebhookSecret = readEnvironmentVariable('GITHUB_WEBHOOK_SECRET')
param githubPersonalAccessToken = readEnvironmentVariable('GITHUB_PERSONAL_ACCESS_TOKEN', '')
